[profile.default]
src = 'contracts'
bytecode_hash = 'none'
solc_version = "0.8.22"
evm_version = 'shanghai'
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "out"

[rpc_endpoints]
mode = "${MODE_MAINNET_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"

mode_archive = "${MODE_MAINNET_ARCHIVE_RPC_URL}"
base_archive = "${BASE_MAINNET_ARCHIVE_RPC_URL}"

# See more config options https://github.com/gakonst/foundry/tree/master/config
