[default]
src = 'contracts_forge'
out = 'artifacts_forge'
libs = ['node_modules']
remappings = ['ds-test/=lib/ds-test/src/', 'forge-std/=lib/forge-std/src/', '@openzeppelin/=../../node_modules/@openzeppelin/','@rari-capital/=../../node_modules/@rari-capital/']
auto_detect_solc = true

# See more config options https://github.com/gakonst/foundry/tree/master/config